### ISSUE TITLE
Safari browser cannot parse the card component from the cdc 

### ISSUE THREAD

**Issue by Jonathan-Snyder** [byuweb/byu-card#5]
# One-Line Summary

Safari throws a parse error when attempting to get 'https://cdn.byu.edu/byu-card/latest/byu-card.js'

# Websites Affected
orca.byu.edu/resourcetest.html
*If this is a bug or styling issue, please list one or more URLs where
we can see the issue.*

# Issue Type

*Is this (add an x in the boxes that apply)*

- [] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [x] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [x] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge,
plus Internet Explorer 11.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Apple Safari
- [ ] Microsoft Edge
- [ ] Microsoft Internet Explorer 11
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [x] Custom Site
- [ ] Don't Know

# Detailed Description

*Tell us all about your problem or feature proposal.*
Safari is not loading some or all of the components styling and it is throwing parse errors and syntax errors for the following:
![screen shot 2017-05-12 at 12 50 55 pm](https://cloud.githubusercontent.com/assets/26228353/26012422/aaafbea6-3711-11e7-9c3a-c4fb3d25abf6.png)
The byu-card component is not loading at all on the page and no styling other than my own fix is working on the page.
**If the issue is with styling, please include screenshots!**

What it looks like in chrome and firefox
![screen shot 2017-05-12 at 12 47 47 pm](https://cloud.githubusercontent.com/assets/26228353/26012282/4e3eb564-3711-11e7-9b69-948839018195.png)
What safari does
![screen shot 2017-05-12 at 12 49 14 pm](https://cloud.githubusercontent.com/assets/26228353/26012338/76c19826-3711-11e7-881b-0b4a26944b57.png)

What I am using for connecting with the cdn:
rel="stylesheet" href="https://cdn.byu.edu/byu-theme-components/latest/byu-theme-components.min.css"
rel="stylesheet" href="https://cdn.byu.edu/byu-card/latest/byu-card.js"

**Comment by ThatJoeMoore** [comment]
Could you post the imports you have in your <head>?  Also, is this available on a public server, or are you developing locally?  The URL in the issue doesn't exist.

I ask because I've been unable to duplicate this locally, so I'm interested in seeing what you're doing differently.

**Comment by Jonathan-Snyder** [comment]
I updated the issue with the correct url, @ThatJoeMoore what do you mean by imports?

**Comment by rburkey87** [comment]
@Jonathan-Snyder - I'm not seeing the issue on your site. Are you still having issues with it? Considering how long ago this was posted, I imagine the components updates may have fixed the problem a while ago.

**Comment by Jonathan-Snyder** [comment]
I still get the issue with safari on my mac, now works fine with firefox and chrome. I still get error messages about how it can't parse the stylesheet. 

Says it has 2 errors: Unexpected use of reserved word 'let in strict mode and Did not parse stylesheet at 'https://cdn.byu.edu/byu-card/latest/byu-card.js' because non css MIME types are not allowed in strict mode.

At this point I don't know what is causing the issue.

**Comment by rburkey87** [comment]
@Jonathan-Snyder 

Two things that I think might be causing the issue:
You mentioned that you used the following to connect to the cdn:
`What I am using for connecting with the cdn:
rel="stylesheet" href="https://cdn.byu.edu/byu-theme-components/latest/byu-theme-components.min.css"
rel="stylesheet" href="https://cdn.byu.edu/byu-card/latest/byu-card.js"`

You'll want both the js and the css to reference byu-card (since one is referencing components, though you'll want to also reference components css & js separately). You are also referencing JS as a stylesheet. Try this:
`<script async src="https://cdn.byu.edu/byu-card/latest/byu-card.min.js"></script>`

I noticed, however, that the byu-card is not generating a css file (only the original scss files), so I'm fixing that and I'll let you know as soon as it's updated, but the JS as a stylesheet should be causing your error.

**Comment by rburkey87** [comment]
@Jonathan-Snyder 

Okay, the gulpfile has been fixed so you can now reference:
`<link rel="stylesheet" href="https://cdn.byu.edu/byu-card/latest/byu-card.min.css" />`

**Comment by rburkey87** [comment]
Let me know if this fixed your issue :)
