### ISSUE TITLE
Improve documentation.

### ISSUE THREAD

**Issue by brennonbrimhall** [byuweb/byu-card#6]
We've got some great resources available to help people know how to use the header, footer, and other BYU web components.  In contrast, this card system doesn't have a detailed README, project wiki, link to relevant documentation, etc.  As a potential user, I'm not sure I know how to use it.

**Comment by ThatJoeMoore** [comment]
Yeah, we've been pretty focused on the main theme components.  I'll see what we can do to get some docs published in the next little bit.

**Comment by brennonbrimhall** [comment]
Thanks for looking into this!  Let me know if there's anything I can do on my end to help.

**Comment by blakemorgan** [comment]
@brennonbrimhall Feel free to join the engineering group channel on the Web Community slack team. We'd love your input and assistance.

**Comment by katrialesser** [comment]
We've sufficiently updated the documentation with normal default styling information as well as options we are adding this week.
