### ISSUE TITLE
Remove use of eval()

### ISSUE THREAD

**Issue by brennonbrimhall** [byuweb/byu-card#8]
While trying to implement this card component, I found that our current Content Security Policy was interfering with proper rendering.  It looks like this requires `unsafe-eval` to be included.

**Comment by ThatJoeMoore** [comment]
This was resolved in byuweb/web-component-loader-generator@cdb8fb0 .  @katrialesser , if you run an `npm update` and then run the build again, it will resolve this issue.

**Comment by brennonbrimhall** [comment]
@katrialesser and @ThatJoeMoore - is a recompile/`npm update` on this something that's easy for you?  If not, we probably will bundle our own version of the JS for the meantime.

**Comment by ThatJoeMoore** [comment]
It's pretty easy.  I deferred to Katria, since she's the main developer on this component, but I'll go ahead and run the compile/update now.

**Comment by brennonbrimhall** [comment]
iMuchas gracias!  Let me know when you've updated so I can confirm on my end and we can get this ticket closed.

**Comment by ThatJoeMoore** [comment]
Okay, I've opened a PR.  @katrialesser , could you take a look?
